FROM alpine:3.20

RUN apk add --no-cache nginx && \
  ln -s /dev/stdout /var/log/nginx/access.log && \
  ln -s /dev/stderr /var/log/nginx/error.log

COPY nginx/default.conf /etc/nginx/http.d/default.conf
COPY nginx/nginx.conf /etc/nginx/nginx.conf

CMD nginx -g "daemon off;"
